# Generated by Django 5.0.7 on 2024-08-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0003_learnerprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnerprogress',
            options={'verbose_name_plural': 'LearnerProgress'},
        ),
    ]
