# Generated by Django 5.0.7 on 2024-08-07 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0004_alter_learnerprogress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprogress',
            name='period_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
