# Generated by Django 5.0.7 on 2024-08-07 20:08

import onCourse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0005_alter_learnerprogress_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprogress',
            name='period_end',
            field=models.DateField(default=onCourse.models.default_end_date),
        ),
    ]
