# Generated by Django 5.0.7 on 2024-08-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0006_alter_learnerprogress_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='onCourse.user'),
        ),
    ]
