# Generated by Django 5.0.7 on 2024-08-07 20:52

import datetime
import onCourse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0007_alter_learner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprogress',
            name='period_end',
            field=models.DateField(blank=True, default=onCourse.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='learnerprogress',
            name='period_start',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
