# Generated by Django 5.0.7 on 2024-08-08 21:00

import datetime
import onCourse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0008_alter_learnerprogress_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprogress',
            name='period_end',
            field=models.DateField(default=onCourse.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='learnerprogress',
            name='period_start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('learner', 'Learner'), ('teacher', 'Teacher'), ('parent', 'Parent')], default=1, max_length=10),
        ),
    ]
