# Generated by Django 5.0.7 on 2024-08-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0009_alter_learnerprogress_period_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressReport',
        ),
    ]
