# Generated by Django 5.0.7 on 2024-08-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0010_delete_progressreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ussdrequest',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ussdrequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsapprequest',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsapprequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='onCourse.user'),
        ),
        migrations.AlterField(
            model_name='learnerprogress',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='onCourse.learner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('learner', 'Learner'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='learner', max_length=10),
        ),
    ]
