# Generated by Django 5.0.7 on 2024-08-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0011_learnerprogress_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprogress',
            name='updated_at',
        ),
    ]
