# Generated by Django 5.0.7 on 2024-08-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0014_remove_learnerprogress_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hods', to='onCourse.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='onCourse.user')),
            ],
        ),
    ]
