# Generated by Django 5.0.7 on 2024-08-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0015_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprogress',
            name='concepts_not_grasped',
            field=models.TextField(blank=True),
        ),
    ]
