# Generated by Django 5.0.7 on 2024-08-10 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0016_alter_learnerprogress_concepts_not_grasped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='learnerprogress',
            name='concepts_grasped',
        ),
        migrations.RemoveField(
            model_name='learnerprogress',
            name='concepts_not_grasped',
        ),
        migrations.AlterField(
            model_name='conceptgrasp',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.concept'),
        ),
        migrations.AddField(
            model_name='concept',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.subject'),
        ),
        migrations.AlterField(
            model_name='conceptgrasp',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.subject'),
        ),
        migrations.AlterField(
            model_name='learnerprogress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.subject'),
        ),
        migrations.AddField(
            model_name='learnerprogress',
            name='concepts_grasped',
            field=models.ManyToManyField(related_name='grasped_in_progress', to='onCourse.concept'),
        ),
        migrations.AddField(
            model_name='learnerprogress',
            name='concepts_not_grasped',
            field=models.ManyToManyField(blank=True, related_name='not_grasped_in_progress', to='onCourse.concept'),
        ),
    ]
