# Generated by Django 5.0.7 on 2024-08-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0017_concept_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprogress',
            name='concept_grasp',
            field=models.ForeignKey(default='yes', on_delete=django.db.models.deletion.CASCADE, to='onCourse.conceptgrasp'),
            preserve_default=False,
        ),
    ]
