# Generated by Django 5.0.7 on 2024-08-11 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0018_learnerprogress_concept_grasp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprogress',
            name='concept_grasp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onCourse.conceptgrasp'),
        ),
    ]
