# Generated by Django 5.0.7 on 2024-08-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0019_alter_learnerprogress_concept_grasp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprogress',
            name='concept_grasp',
        ),
        migrations.RemoveField(
            model_name='learnerprogress',
            name='concepts_grasped',
        ),
        migrations.RemoveField(
            model_name='learnerprogress',
            name='concepts_not_grasped',
        ),
        migrations.AddField(
            model_name='learnerprogress',
            name='concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onCourse.concept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnerprogress',
            name='grasp_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
    ]
