# Generated by Django 5.0.7 on 2024-08-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0022_districtoffice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='onCourse.teacher'),
            preserve_default=False,
        ),
    ]
