# Generated by Django 5.0.7 on 2024-08-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0023_learner_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='onCourse.parent'),
        ),
    ]
