# Generated by Django 5.0.7 on 2024-08-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0024_alter_learner_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='onCourse.subject'),
        ),
    ]
