# Generated by Django 5.0.7 on 2024-08-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0026_learnergrade_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grasp_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('performance_score', models.FloatField()),
                ('school_comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.concept')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.subject')),
            ],
            options={
                'verbose_name': 'School Progress',
                'verbose_name_plural': 'School Progresses',
                'ordering': ['-date'],
            },
        ),
    ]
