# Generated by Django 5.0.7 on 2024-08-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0027_schoolprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_messages', to='onCourse.user')),
                ('learner_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.learnerprogress')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_messages', to='onCourse.user')),
            ],
        ),
    ]
