# Generated by Django 5.0.7 on 2024-08-17 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0030_learnerprogress_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprogress',
            options={'ordering': ['-date'], 'verbose_name': 'School Progress', 'verbose_name_plural': 'School Progress'},
        ),
        migrations.CreateModel(
            name='LearnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary')], max_length=60)),
                ('grade', models.CharField(max_length=20)),
                ('extra_tutorials', models.BooleanField(default=False)),
                ('previous_school', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('learner_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
