# Generated by Django 5.0.7 on 2024-08-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0031_alter_schoolprogress_options_learnerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerinfo',
            name='learner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='onCourse.learner'),
        ),
    ]
