# Generated by Django 5.0.7 on 2024-08-20 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0032_alter_learnerinfo_learner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('date', models.DateField()),
                ('grade', models.CharField(max_length=20)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.learner')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField()),
                ('predicted_score', models.FloatField()),
                ('comparison_to_average', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onCourse.learner')),
            ],
        ),
    ]
