# Generated by Django 5.0.7 on 2024-08-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onCourse', '0033_learnerperformance_performanceanalytics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnerinfo',
            options={'verbose_name_plural': 'Learner Information'},
        ),
    ]
